# Generated by Django 3.2.12 on 2022-04-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=255)),
                ('car_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('car_photo_1', models.ImageField(default='default.jpg', upload_to='photos/%Y/%m/%d/')),
                ('car_photo_2', models.ImageField(default='default.jpg', upload_to='photos/%Y/%m/%d/')),
                ('car_photo_3', models.ImageField(default='default.jpg', upload_to='photos/%Y/%m/%d/')),
                ('car_photo_4', models.ImageField(default='default.jpg', upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
