# Generated by Django 3.2.12 on 2022-04-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0006_auto_20220412_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='2', max_length=10),
        ),
    ]
