# Generated by Django 3.2.12 on 2022-04-12 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0007_alter_car_doors'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='Sedan', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='milage',
            field=models.CharField(default='Sedan', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='no_of_owners',
            field=models.CharField(default='Sedan', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='passengers',
            field=models.CharField(default='Sedan', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='vin_no',
            field=models.CharField(default='Sedan', max_length=100),
        ),
    ]
